### ISSUE TITLE
Add rdrand support

### ISSUE THREAD

**Issue by Whissi** [mgorny/cpuid2cpuflags#1]
Any chance to get detection for rdrand?

**Comment by ghost** [comment]
https://en.wikipedia.org/wiki/RdRand#Reception

**Comment by Whissi** [comment]
Well, isn't it up to the user to decide what he/she wants to use? For example dev-libs/json-c could make use of it.

**Comment by ghost** [comment]
Well, the fastest way to power-off certain computer is to pull out the power cord, but there should be a warning sign before doing so and what will be the side effects afterwards.

**Comment by mgorny** [comment]
I'm sorry I didn't reply earlier but apparently I wasn't watching my own repository for some reason x_x.

As for additional flags, they have to land in profiles/desc first, so you have to follow the usual Gentoo procedure. Plus, in case of x86 they need to be available via CPUID.
