### ISSUE TITLE
Output is not perfectly ready for Portage

### ISSUE THREAD

**Issue by spidey** [mgorny/cpuid2cpuflags#11]
I don't know about Paludis, but portage config files use key=value format for configuration on make.conf and category/package flags for per package configuration files, but the tool is currently printing in the var:values format.

Easy enough to edit by hand, but easy enough to fix too, either on the README or the program itself. Maybe adding a flag to make it more script friendly, with which it would only print the flags.

**Comment by mgorny** [comment]
README says how to use it. `make.conf` is just horribly bad design and you shouldn't use it.

**Comment by spidey** [comment]
I was actually wrong, package.use DOES permit "key: value" notation for expanded USE flags, didn't know about it (I'm coming back to Gentoo after years without touching it). Sorry for it.

The confusion came from the Gentoo Wiki that didn't update the main instructions for the new version of the tool. https://wiki.gentoo.org/wiki/CPU_FLAGS_X86

**Comment by spidey** [comment]
Could you detail why you think package.use is better than make.conf for this setting?

**Comment by mgorny** [comment]
Because make.conf is non-incremental (it always overrides the default instead of letting you modify it) and has horrible broken syntax on top of two layers of broken parsers (don't get me started on this, I've practically abandoned flaggie because of impossibility of getting make.conf right).
