### ISSUE TITLE
output format does not match make.conf syntax

### ISSUE THREAD

**Issue by petaflot** [mgorny/cpuid2cpuflags#17]
```
# cpuid2cpuflags
CPU_FLAGS_X86: aes avx avx2 f16c fma3 mmx mmxext pclmul popcnt rdrand sse sse2 sse3 sse4_1 sse4_2 ssse3

# cpuid2cpuflags >> /etc/portage/make.conf
```

requires editing make.conf... IMHO it would be better to have sth like

```
# cpuid2cpuflags
CPU_FLAGS_X86="aes avx avx2 f16c fma3 mmx mmxext pclmul popcnt rdrand sse sse2 sse3 sse4_1 sse4_2 ssse3"
```

**Comment by mgorny** [comment]
As the README says, the format is suited for `package.use`, not that ugly crap of `make.conf`.

**Comment by Forza-tng** [comment]
> As the README says, the format is suited for `package.use`, not that ugly crap of `make.conf`.

I've been using make.conf since day one, so I'm really used to make.conf simply by old habits :)

Would you consider at least mention if having `CPU_FLAGS_X86=""` in make conf is deprecated in favour of package.use (and why)?

**Comment by petaflot** [comment]
@mgorny 
> As the README says, the format is suited for package.use, not that ugly crap of make.conf.

why... do you set flags per-package?

**Comment by mgorny** [comment]
```
*/* CPU_FLAGS_X86: ...
```

**Comment by petaflot** [comment]
still requires editing your file... it would be better to have sth like
```
# cpuid2cpuflags
*/* CPU_FLAGS_X86: aes avx avx2 f16c fma3 mmx mmxext pclmul popcnt rdrand sse sse2 sse3 sse4_1 sse4_2 ssse3

# cpuid2cpuflags >> /etc/portage/package.use/all_packages
```
and since make.conf is for all packages... I really don't understand why you stick to package.use and what you find so ugly with make.conf. anyway... you have your habits and I understand.

how about supporting a `-m` (or `--make.conf` for the long version) flag?

**Comment by mgorny** [comment]
`make.conf` is broken and can't handle incremental flags for `USE_EXPAND` at all, which is frequently causing problems for users.

**Comment by petaflot** [comment]
fair enough. and if package.use does it, then I see no reason to fix make.conf. thanks for the explanation Michal

wouldn't it be good to add a note in the handbook (and make.conf?) about this problem, so setting USE in make.conf can slowly deprecate?

**Comment by mgorny** [comment]
I'm trying to figure out how to best go about announcing the deprecation. Unfortunately, I'm simultaneously flooded with Gentoo work and burned out.

**Comment by petaflot** [comment]
> I'm trying to figure out how to best go about announcing the deprecation. 

XD

> Unfortunately, I'm simultaneously flooded with Gentoo work and burned out.

Take some rest dude, I'm sure there are others who'll step up to give a hand if you step back a little. It's not like the penguin's gonna die if you give it some [slack](http://www.slackware.com/), or is it?
