### ISSUE TITLE
Add support for FreeBSD

### ISSUE THREAD

**Issue by danfe** [mgorny/cpuid2cpuflags#19]
I've played with it on ARM today and it seems to work.  Two changes were required:

  - Replace `getauxval(3)`, a non-standard glibc extension, with our native `elf_aux_info(3)` call
  - Return features supported by the specific machine processor architecture rather than the hardware platform, because the latter is too vague on FreeBSD: it always returns just `arm` without any version (generation)

The actual patch is [here](https://cgit.freebsd.org/ports/tree/sysutils/cpuid2cpuflags/files/patch-src_hwcap.c).

**Comment by mgorny** [comment]
Do you have anything against submitting that as a PR?

**Comment by danfe** [comment]
> Do you have anything against submitting that as a PR?

Well, I don't really like them (nor was I sure if you'd like the patch in the first place), but owing to your reputation and politeness, I will. :-)

**Comment by mgorny** [comment]
Thanks. I'll probably request some changes, if you don't mind me, though. If you do, I can take it from there — or you can just mail me the patch, my main concern is just want to get the attribution right.

**Comment by danfe** [comment]
> I'll probably request some changes, if you don't mind me, though.

Understood (and expected).  I don't mind, let's resolve this to mutual happiness.

**Comment by danfe** [comment]
Fixed with 9d1b472, closing.
