### ISSUE TITLE
cmake conversion.. via autocmake.py 

### ISSUE THREAD

**Issue by necrose99** [mgorny/cpuid2cpuflags#22]
[CMakeLists.txt](https://github.com/projg2/cpuid2cpuflags/files/10807459/CMakeLists.txt)
 
#https://github.com/fritzone/autocmake

https://cmake.org/cmake/help/v3.7/module/CPackDeb.html or CPackrpm 
toys like **binary-gentoo** on pypi for say a cheap  web binhost or renting gravaton2 arm64 docker  to run gentoo builds might be of some small use to where one is rammed with rpm/or deb vps servers as a defacto... 
or github actions etc...  build gentoo toys >>> github/lfs .... ( @spreequalle/gentoo-binhost )
(**resolve march native** is python based ..  binary-gentoo has want of cpuid2cpuflags as well ) 

hopefully cmakes multi-arch abilities helps add mor arches...  whom knows 
its a start anyways.

**Comment by mgorny** [comment]
I don't understand what you're trying to say. Using CMake is not a goal. There's no benefit from making tiny tools depend on huge enterprise-grade build systems with tons of features they'll never use.
