### ISSUE TITLE
Compile on arm with musl libc

### ISSUE THREAD

**Issue by doughdemon** [mgorny/cpuid2cpuflags#3]
Seems to work fine, except that the __GLIBC__ test in src/arm.c is counter-productive...

**Comment by mgorny** [comment]
`getauxval()` is glibc-only per the manpage. If musl supports it (does it provide both AT_HWCAP and AT_HWCAP2?), then please supply me the definition that I could use to detect that.

**Comment by doughdemon** [comment]
> `getauxval()` is glibc-only per the manpage. If musl supports it
> (does it provide both AT_HWCAP and AT_HWCAP2?),

yes.

> then please supply me the definition that I could use to detect that.

You could check for <sys/auxv.h> in configure.

**Comment by mgorny** [comment]
Well, I guess that makes sense. FWICS, Android seems to have that header and function as well.

**Comment by mgorny** [comment]
Could you test the current git (-9999)?

**Comment by doughdemon** [comment]
Current git works. Thanks!

**Comment by mgorny** [comment]
Resolving then. I'll include it in the next release. Feel free to ping me in a few days if nothing else comes up for the release.
