### ISSUE TITLE
enable simple copy and paste

### ISSUE THREAD

**Issue by jonasstein** [mgorny/cpuid2cpuflags#7]
I suggest to adjust the format a little bit to enable simple copy and paste

Output now:
`CPU_FLAGS_X86: aes avx f16c mmx mmxext pclmul popcnt sse sse2 sse3 sse4_1 sse4_2 ssse3`

What I suggest:
`CPU_FLAGS_X86="aes avx f16c mmx mmxext pclmul popcnt sse sse2 sse3 sse4_1 sse4_2 ssse3"`

**Comment by mgorny** [comment]
Setting this via make.conf is wrong. Use package.use like normal package managers do.

**Comment by jonasstein** [comment]
This is interesting. I did not know that before. https://wiki.gentoo.org/wiki/CPU_FLAGS_X86
and https://wiki.gentoo.org/wiki//etc/portage/make.conf#CPU_FLAGS_X86 needs updating then.
